version: '3.4'

services:
  marten-app: 
    depends_on:
     - "marten-db"
    container_name: marten_api
    ports:
     - "5000:80"
    build: .
    environment:
     - ConnectionStrings__Marten=username=postgres;password=wc3alive;Server=marten_db;Port=5432;Database=postgres;
  
  marten-db:
    image: postgres:latest
    container_name: marten_db
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=wc3alive
     - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - app_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    container_name: marten_proxy
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf

volumes:
    app_data: